version: "3"
services:
  rabbitMQ:
   image: rabbitmq:3-management
   container_name: 'rabbitmq_container'
   environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
   ports:
    - 8050:15672
    - 5672:5672
   expose:
    - 5672
   networks: 
    - epozoristenet 

  #mssql docker
  epozoriste-sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - epozoristenet

  epozoriste-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=epozoriste-sql,1433;Database=ePozoriste;User=sa;Password=QWElkj132!;ConnectRetryCount=0;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 5192:5192
    networks:
      - epozoristenet
    links:
      - epozoriste-sql
    depends_on:
      - epozoriste-sql
      - rabbitMQ

  rabbitmq-service:
    restart: on-failure
    build:
      context: .
      dockerfile: ./ePozoriste.Subscriber/Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
      - OUTLOOK_MAIL=epozoriste@outlook.com
      - OUTLOOK_PASS=Test-Test123!
    depends_on:
      - rabbitMQ
      - epozoriste-sql
      - epozoriste-api
    networks:
      - epozoristenet
    ports:
      - 7101:80

networks:
  epozoristenet:
    driver: bridge